version: '3.3'

services:
    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/data/application:delegated
            - /data/application/var

    nginx:
        image: nginx:alpine
        volumes:
            - ./:/data/application
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"